#!/usr/bin/env python3
"""Generates supabase/seed.sql from a curated movie dataset.
Run: python3 scripts/gen_seed.py > supabase/seed.sql
"""

def esc(s: str) -> str:
    return s.replace("'", "''")

def s(v) -> str:
    return f"'{esc(str(v))}'"

def arr(items) -> str:
    return "ARRAY[" + ", ".join(s(i) for i in items) + "]::text[]"

GENRES = [
    ("action", "Action"),
    ("comedy", "Comedy"),
    ("drama", "Drama"),
    ("horror", "Horror"),
    ("scifi", "Sci-Fi"),
    ("romance", "Romance"),
    ("thriller", "Thriller"),
    ("animation", "Animation"),
    ("fantasy", "Fantasy"),
    ("documentary", "Documentary"),
]

# title, year, director, runtime, rating, primary_genre, [all genres], [mood tags], blurb
MOVIES = [
    ("Die Hard", 1988, "John McTiernan", 132, 8.2, "action", ["action", "thriller"],
     ["edge-of-seat", "funny"],
     "One cop, one skyscraper, and a Christmas party that goes very wrong — the template every action movie since has been copying."),
    ("Mad Max: Fury Road", 2015, "George Miller", 120, 8.4, "action", ["action", "scifi"],
     ["edge-of-seat", "epic"],
     "A two-hour chase across the desert that somehow still finds time for one of the decade's best-drawn characters."),
    ("The Matrix", 1999, "The Wachowskis", 136, 8.5, "action", ["action", "scifi"],
     ["mind-bending", "cerebral"],
     "Bullet time, red pills, and a paranoid thesis about reality dressed up as the coolest action movie of its era."),
    ("Terminator 2: Judgment Day", 1991, "James Cameron", 137, 8.6, "action", ["action", "scifi"],
     ["edge-of-seat", "epic"],
     "The rare sequel that out-does the original, with special effects that still hold up decades later."),
    ("John Wick", 2014, "Chad Stahelski", 101, 7.9, "action", ["action", "thriller"],
     ["edge-of-seat"],
     "A grieving hitman comes out of retirement over a stolen car and a dead dog, and the genre hasn't been the same since."),
    ("Raiders of the Lost Ark", 1981, "Steven Spielberg", 115, 8.5, "action", ["action", "fantasy"],
     ["nostalgic", "epic"],
     "Nazis, boulders, and a whip-cracking archaeologist — pure matinee adventure with barely a wasted frame."),
    ("Speed", 1994, "Jan de Bont", 116, 7.3, "action", ["action", "thriller"],
     ["edge-of-seat"],
     "A bus that can't slow below fifty is the entire premise, and somehow that's more than enough."),
    ("Mission: Impossible - Fallout", 2018, "Christopher McQuarrie", 147, 7.8, "action", ["action", "thriller"],
     ["edge-of-seat", "epic"],
     "Six films in, and the stunts still escalate — this one has Tom Cruise flying a helicopter through a canyon himself."),

    ("Airplane!", 1980, "Jim Abrahams", 88, 7.7, "comedy", ["comedy"],
     ["funny", "so-bad-its-good"],
     "A disaster-movie spoof that fires sight gags so fast you'll miss half of them laughing at the last one."),
    ("Superbad", 2007, "Greg Mottola", 113, 7.6, "comedy", ["comedy"],
     ["funny", "nostalgic"],
     "Two best friends spend one chaotic night trying to buy alcohol before they leave for separate colleges."),
    ("Groundhog Day", 1993, "Harold Ramis", 101, 8.0, "comedy", ["comedy", "fantasy"],
     ["funny", "heartwarming"],
     "A cynical weatherman relives the same small-town day over and over until he finally learns something from it."),
    ("The Grand Budapest Hotel", 2014, "Wes Anderson", 99, 8.1, "comedy", ["comedy", "drama"],
     ["quirky", "cozy"],
     "A concierge and his lobby boy get tangled in an art heist, a murder, and a prison break, all in pastel symmetry."),
    ("Bridesmaids", 2011, "Paul Feig", 125, 6.8, "comedy", ["comedy", "romance"],
     ["funny", "heartwarming"],
     "A maid of honor's life falls apart in real time while she tries to hold a wedding together."),
    ("Dr. Strangelove", 1964, "Stanley Kubrick", 95, 8.5, "comedy", ["comedy", "drama"],
     ["so-bad-its-good", "cerebral"],
     "A war room farce about the men one phone call away from ending the world, and how little it would take."),
    ("Anchorman: The Legend of Ron Burgundy", 2004, "Adam McKay", 94, 7.2, "comedy", ["comedy"],
     ["funny", "quirky"],
     "A 1970s San Diego newsman's fragile ego meets a rival anchorwoman, with a jazz flute solo along the way."),
    ("Some Like It Hot", 1959, "Billy Wilder", 121, 8.2, "comedy", ["comedy", "romance"],
     ["funny", "nostalgic"],
     "Two musicians witness a mob hit and go on the run disguised as an all-female band."),

    ("The Godfather", 1972, "Francis Ford Coppola", 175, 9.2, "drama", ["drama", "thriller"],
     ["epic", "cerebral"],
     "A crime family's succession story, told with more patience and weight than almost anything else in the genre."),
    ("Forrest Gump", 1994, "Robert Zemeckis", 142, 8.0, "drama", ["drama", "romance"],
     ["heartwarming", "nostalgic"],
     "A slow-witted, kind-hearted man stumbles through three decades of American history and comes out the other side happy."),
    ("Schindler's List", 1993, "Steven Spielberg", 195, 9.0, "drama", ["drama"],
     ["heavy", "cerebral"],
     "A war profiteer's slow moral awakening, shot in stark black and white that never lets you look away."),
    ("12 Angry Men", 1957, "Sidney Lumet", 96, 8.9, "drama", ["drama", "thriller"],
     ["cerebral", "edge-of-seat"],
     "Twelve jurors, one hot room, and a single holdout who refuses to send a boy to the chair without talking it through."),
    ("The Shawshank Redemption", 1994, "Frank Darabont", 142, 9.3, "drama", ["drama"],
     ["heartwarming", "epic"],
     "A wrongly convicted banker spends two decades in prison, patiently building the means to walk out on his own terms."),
    ("There Will Be Blood", 2007, "Paul Thomas Anderson", 158, 8.2, "drama", ["drama"],
     ["dark", "cerebral"],
     "An oilman's ambition curdles into something monstrous, set to one of the great unsettling scores in film."),
    ("Moonlight", 2016, "Barry Jenkins", 111, 7.4, "drama", ["drama", "romance"],
     ["heavy", "tearjerker"],
     "One boy's life told in three chapters, each one quietly reshaping who he's allowed to become."),
    ("Parasite", 2019, "Bong Joon-ho", 132, 8.5, "drama", ["drama", "thriller"],
     ["dark", "cerebral"],
     "A poor family cons its way into a rich household's employ, and the class satire turns into something much sharper."),

    ("The Shining", 1980, "Stanley Kubrick", 146, 8.4, "horror", ["horror", "drama"],
     ["scary", "dark"],
     "A winter caretaker's slow unraveling in an empty hotel, filmed with a dread that never lets up."),
    ("Get Out", 2017, "Jordan Peele", 104, 7.7, "horror", ["horror", "thriller"],
     ["scary", "cerebral"],
     "A weekend meeting the girlfriend's parents turns into a horror movie about being the only Black guest at the party."),
    ("Hereditary", 2018, "Ari Aster", 127, 7.3, "horror", ["horror", "drama"],
     ["scary", "dark"],
     "A family tragedy uncovers something much older and much worse lurking in their bloodline."),
    ("Alien", 1979, "Ridley Scott", 117, 8.5, "horror", ["horror", "scifi"],
     ["scary", "edge-of-seat"],
     "A cargo ship's crew realizes too late that something got on board with them, in space where no one can hear you scream."),
    ("A Quiet Place", 2018, "John Krasinski", 90, 7.5, "horror", ["horror", "thriller"],
     ["scary", "edge-of-seat"],
     "A family survives blind monsters that hunt by sound alone, which means every scene is nearly silent."),
    ("The Exorcist", 1973, "William Friedkin", 122, 8.1, "horror", ["horror", "drama"],
     ["scary", "dark"],
     "A mother watches her daughter change into something else entirely, and calls in the priests as a last resort."),
    ("Psycho", 1960, "Alfred Hitchcock", 109, 8.5, "horror", ["horror", "thriller"],
     ["scary", "cerebral"],
     "A secretary on the run checks into a roadside motel run by a young man very attached to his mother."),

    ("Blade Runner", 1982, "Ridley Scott", 117, 8.1, "scifi", ["scifi", "thriller"],
     ["cerebral", "dark"],
     "A bounty hunter tracks synthetic humans through a rain-soaked future city and starts to question what makes anyone real."),
    ("Interstellar", 2014, "Christopher Nolan", 169, 8.6, "scifi", ["scifi", "drama"],
     ["epic", "tearjerker"],
     "A father leaves his kids behind to find humanity a new home, and time itself becomes the story's cruelest obstacle."),
    ("Arrival", 2016, "Denis Villeneuve", 116, 7.9, "scifi", ["scifi", "drama"],
     ["cerebral", "tearjerker"],
     "A linguist tries to talk to aliens before the world's militaries decide to shoot first."),
    ("2001: A Space Odyssey", 1968, "Stanley Kubrick", 149, 8.3, "scifi", ["scifi"],
     ["cerebral", "epic"],
     "From bone tools to star gates, a nearly wordless history of intelligence and the machines that might replace it."),
    ("Inception", 2010, "Christopher Nolan", 148, 8.8, "scifi", ["scifi", "thriller"],
     ["mind-bending", "cerebral"],
     "A thief who steals secrets from dreams takes one last job: planting an idea instead of stealing one."),
    ("Dune", 2021, "Denis Villeneuve", 155, 8.0, "scifi", ["scifi", "drama"],
     ["epic", "cerebral"],
     "A duke's son is thrown into a desert planet's politics, religion, and the only resource the galaxy actually needs."),
    ("E.T. the Extra-Terrestrial", 1982, "Steven Spielberg", 115, 7.9, "scifi", ["scifi", "drama"],
     ["heartwarming", "nostalgic"],
     "A stranded alien and a lonely kid become best friends, and a flying bicycle becomes cinema history."),
    ("Star Wars: A New Hope", 1977, "George Lucas", 121, 8.6, "scifi", ["scifi", "fantasy"],
     ["epic", "nostalgic"],
     "A farm boy, a smuggler, and a princess take on an empire, and the modern blockbuster is born."),

    ("Before Sunrise", 1995, "Richard Linklater", 101, 8.1, "romance", ["romance", "drama"],
     ["romantic", "cozy"],
     "Two strangers meet on a train and spend one night walking Vienna, talking about everything that matters to them."),
    ("Eternal Sunshine of the Spotless Mind", 2004, "Michel Gondry", 108, 8.3, "romance", ["romance", "drama"],
     ["mind-bending", "tearjerker"],
     "An ex-couple erase each other from memory, and the movie argues gently that maybe they shouldn't have."),
    ("Pride & Prejudice", 2005, "Joe Wright", 129, 7.8, "romance", ["romance", "drama"],
     ["romantic", "cozy"],
     "A headstrong woman and a proud, awkward landowner slowly talk themselves out of their own worst assumptions."),
    ("When Harry Met Sally...", 1989, "Rob Reiner", 96, 7.7, "romance", ["romance", "comedy"],
     ["romantic", "funny"],
     "Can men and women ever just be friends? Twelve years of near-misses later, the movie has an answer."),
    ("La La Land", 2016, "Damien Chazelle", 128, 8.0, "romance", ["romance", "drama"],
     ["romantic", "tearjerker"],
     "A jazz pianist and an actress fall in love in Los Angeles while their ambitions quietly pull them apart."),
    ("Notting Hill", 1999, "Roger Michell", 124, 7.2, "romance", ["romance", "comedy"],
     ["romantic", "cozy"],
     "A bookshop owner falls for the most famous actress in the world, which turns out to complicate things."),

    ("Se7en", 1995, "David Fincher", 127, 8.6, "thriller", ["thriller", "horror"],
     ["dark", "edge-of-seat"],
     "Two detectives chase a killer staging murders around the seven deadly sins, right up to an ending that still stings."),
    ("No Country for Old Men", 2007, "Joel and Ethan Coen", 122, 8.2, "thriller", ["thriller", "drama"],
     ["dark", "cerebral"],
     "A hunter finds two million dollars at a drug deal gone wrong, and a hitman with a coin decides what happens next."),
    ("Gone Girl", 2014, "David Fincher", 149, 8.1, "thriller", ["thriller", "drama"],
     ["dark", "edge-of-seat"],
     "A husband becomes the prime suspect when his wife vanishes on their anniversary, and nothing about the case is what it looks like."),
    ("The Silence of the Lambs", 1991, "Jonathan Demme", 118, 8.6, "thriller", ["thriller", "horror"],
     ["dark", "edge-of-seat"],
     "A trainee FBI agent trades information with an imprisoned cannibal to catch a serial killer still out there."),
    ("Prisoners", 2013, "Denis Villeneuve", 153, 8.1, "thriller", ["thriller", "drama"],
     ["dark", "edge-of-seat"],
     "A father takes the search for his missing daughter into his own hands, and the movie asks how far that should go."),
    ("Zodiac", 2007, "David Fincher", 157, 7.7, "thriller", ["thriller", "drama"],
     ["cerebral", "dark"],
     "A cartoonist becomes obsessed with an unsolved serial killer case that slowly consumes his entire life."),

    ("Spirited Away", 2001, "Hayao Miyazaki", 125, 8.6, "animation", ["animation", "fantasy"],
     ["cozy", "epic"],
     "A girl wanders into a bathhouse for spirits and has to work her way free before she forgets her own name."),
    ("Toy Story", 1995, "John Lasseter", 81, 8.3, "animation", ["animation", "comedy"],
     ["heartwarming", "nostalgic"],
     "A cowboy doll's jealousy of the new spaceman toy launches the film that started modern computer animation."),
    ("Spider-Man: Into the Spider-Verse", 2018, "Bob Persichetti, Peter Ramsey, Rodney Rothman", 117, 8.4, "animation", ["animation", "action"],
     ["epic", "funny"],
     "Six Spider-people from six universes have to team up, and the animation reinvents what a superhero movie can look like."),
    ("WALL-E", 2008, "Andrew Stanton", 98, 8.4, "animation", ["animation", "scifi"],
     ["heartwarming", "cozy"],
     "A lonely trash-compacting robot falls for a sleek probe sent to check if Earth can support life again."),
    ("The Iron Giant", 1999, "Brad Bird", 86, 8.1, "animation", ["animation", "scifi"],
     ["heartwarming", "tearjerker"],
     "A boy befriends a giant robot from space and has to convince it — and the paranoid government agent chasing it — that it doesn't have to be a weapon."),
    ("Coco", 2017, "Lee Unkrich, Adrian Molina", 105, 8.4, "animation", ["animation", "fantasy"],
     ["heartwarming", "tearjerker"],
     "A boy who loves music crosses into the Land of the Dead to find the great-great-grandfather his family never talks about."),
    ("Up", 2009, "Pete Docter", 96, 8.3, "animation", ["animation", "drama"],
     ["tearjerker", "heartwarming"],
     "A widower ties thousands of balloons to his house to finally take the trip he and his wife always planned."),

    ("The Lord of the Rings: The Fellowship of the Ring", 2001, "Peter Jackson", 178, 8.9, "fantasy", ["fantasy", "action"],
     ["epic", "cerebral"],
     "A hobbit inherits a ring that has to be destroyed, and eight companions set out with him to make sure it happens."),
    ("Pan's Labyrinth", 2006, "Guillermo del Toro", 118, 8.2, "fantasy", ["fantasy", "drama"],
     ["dark", "cerebral"],
     "A girl retreats into a labyrinth of monsters and impossible tasks to escape her stepfather's fascist household."),
    ("The Princess Bride", 1987, "Rob Reiner", 98, 8.0, "fantasy", ["fantasy", "romance"],
     ["funny", "romantic"],
     "True love, a pirate, a giant, and a Sicilian who should never have gotten involved in a land war in Asia."),
    ("Harry Potter and the Prisoner of Azkaban", 2004, "Alfonso Cuaron", 142, 7.9, "fantasy", ["fantasy"],
     ["cozy", "epic"],
     "A convicted murderer escapes and seems to be hunting Harry, in the series' darkest and most atmospheric entry yet."),
    ("Big Fish", 2003, "Tim Burton", 125, 8.0, "fantasy", ["fantasy", "drama"],
     ["tearjerker", "quirky"],
     "A son tries to separate fact from myth in his dying father's tall tales, and finds the truth matters less than he thought."),

    ("Free Solo", 2018, "Jimmy Chin, Elizabeth Chai Vasarhelyi", 100, 8.1, "documentary", ["documentary"],
     ["edge-of-seat", "inspiring"],
     "A climber attempts to scale a 3,000-foot rock face with no rope and no margin for error, on camera."),
    ("Won't You Be My Neighbor?", 2018, "Morgan Neville", 94, 8.4, "documentary", ["documentary"],
     ["heartwarming", "tearjerker"],
     "A look at the quiet, deliberate kindness behind a children's television host who took kids seriously."),
    ("Amy", 2015, "Asif Kapadia", 128, 7.8, "documentary", ["documentary"],
     ["heavy", "tearjerker"],
     "Built entirely from home video and concert footage, a portrait of a singer the public never really saw clearly."),
    ("13th", 2016, "Ava DuVernay", 100, 8.2, "documentary", ["documentary"],
     ["cerebral", "heavy"],
     "A history of the loophole in the 13th Amendment and the mass incarceration system it helped build."),
    ("Man on Wire", 2008, "James Marsh", 94, 7.9, "documentary", ["documentary"],
     ["inspiring", "edge-of-seat"],
     "The story of the tightrope walk between the Twin Towers, told like a heist film because that's basically what it was."),
]

def sql_num(v):
    return str(v)

# Top-billed cast for each title (voice cast for animation, featured people
# for documentaries), keyed by title.
CAST = {
    "Die Hard": ["Bruce Willis", "Alan Rickman", "Bonnie Bedelia", "Reginald VelJohnson"],
    "Mad Max: Fury Road": ["Tom Hardy", "Charlize Theron", "Nicholas Hoult", "Hugh Keays-Byrne"],
    "The Matrix": ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss", "Hugo Weaving"],
    "Terminator 2: Judgment Day": ["Arnold Schwarzenegger", "Linda Hamilton", "Edward Furlong", "Robert Patrick"],
    "John Wick": ["Keanu Reeves", "Michael Nyqvist", "Alfie Allen", "Willem Dafoe"],
    "Raiders of the Lost Ark": ["Harrison Ford", "Karen Allen", "Paul Freeman", "John Rhys-Davies"],
    "Speed": ["Keanu Reeves", "Sandra Bullock", "Dennis Hopper", "Jeff Daniels"],
    "Mission: Impossible - Fallout": ["Tom Cruise", "Henry Cavill", "Rebecca Ferguson", "Simon Pegg"],
    "Airplane!": ["Robert Hays", "Julie Hagerty", "Leslie Nielsen", "Lloyd Bridges"],
    "Superbad": ["Jonah Hill", "Michael Cera", "Christopher Mintz-Plasse", "Seth Rogen"],
    "Groundhog Day": ["Bill Murray", "Andie MacDowell", "Chris Elliott", "Stephen Tobolowsky"],
    "The Grand Budapest Hotel": ["Ralph Fiennes", "Tony Revolori", "Saoirse Ronan", "Adrien Brody"],
    "Bridesmaids": ["Kristen Wiig", "Maya Rudolph", "Rose Byrne", "Melissa McCarthy"],
    "Dr. Strangelove": ["Peter Sellers", "George C. Scott", "Sterling Hayden", "Slim Pickens"],
    "Anchorman: The Legend of Ron Burgundy": ["Will Ferrell", "Christina Applegate", "Paul Rudd", "Steve Carell"],
    "Some Like It Hot": ["Marilyn Monroe", "Tony Curtis", "Jack Lemmon", "Joe E. Brown"],
    "The Godfather": ["Marlon Brando", "Al Pacino", "James Caan", "Diane Keaton"],
    "Forrest Gump": ["Tom Hanks", "Robin Wright", "Gary Sinise", "Sally Field"],
    "Schindler's List": ["Liam Neeson", "Ben Kingsley", "Ralph Fiennes", "Embeth Davidtz"],
    "12 Angry Men": ["Henry Fonda", "Lee J. Cobb", "Martin Balsam", "E.G. Marshall"],
    "The Shawshank Redemption": ["Tim Robbins", "Morgan Freeman", "Bob Gunton", "William Sadler"],
    "There Will Be Blood": ["Daniel Day-Lewis", "Paul Dano", "Kevin J. O'Connor", "Ciarán Hinds"],
    "Moonlight": ["Mahershala Ali", "Naomie Harris", "Trevante Rhodes", "Ashton Sanders"],
    "Parasite": ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong", "Choi Woo-shik"],
    "The Shining": ["Jack Nicholson", "Shelley Duvall", "Danny Lloyd", "Scatman Crothers"],
    "Get Out": ["Daniel Kaluuya", "Allison Williams", "Bradley Whitford", "Catherine Keener"],
    "Hereditary": ["Toni Collette", "Alex Wolff", "Milly Shapiro", "Gabriel Byrne"],
    "Alien": ["Sigourney Weaver", "Tom Skerritt", "John Hurt", "Ian Holm"],
    "A Quiet Place": ["Emily Blunt", "John Krasinski", "Millicent Simmonds", "Noah Jupe"],
    "The Exorcist": ["Ellen Burstyn", "Max von Sydow", "Linda Blair", "Jason Miller"],
    "Psycho": ["Anthony Perkins", "Janet Leigh", "Vera Miles", "John Gavin"],
    "Blade Runner": ["Harrison Ford", "Rutger Hauer", "Sean Young", "Daryl Hannah"],
    "Interstellar": ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine"],
    "Arrival": ["Amy Adams", "Jeremy Renner", "Forest Whitaker", "Michael Stuhlbarg"],
    "2001: A Space Odyssey": ["Keir Dullea", "Gary Lockwood", "William Sylvester", "Douglas Rain"],
    "Inception": ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page", "Tom Hardy"],
    "Dune": ["Timothée Chalamet", "Rebecca Ferguson", "Oscar Isaac", "Zendaya"],
    "E.T. the Extra-Terrestrial": ["Henry Thomas", "Drew Barrymore", "Dee Wallace", "Robert MacNaughton"],
    "Star Wars: A New Hope": ["Mark Hamill", "Harrison Ford", "Carrie Fisher", "Alec Guinness"],
    "Before Sunrise": ["Ethan Hawke", "Julie Delpy"],
    "Eternal Sunshine of the Spotless Mind": ["Jim Carrey", "Kate Winslet", "Kirsten Dunst", "Mark Ruffalo"],
    "Pride & Prejudice": ["Keira Knightley", "Matthew Macfadyen", "Rosamund Pike", "Donald Sutherland"],
    "When Harry Met Sally...": ["Billy Crystal", "Meg Ryan", "Carrie Fisher", "Bruno Kirby"],
    "La La Land": ["Ryan Gosling", "Emma Stone", "John Legend", "J.K. Simmons"],
    "Notting Hill": ["Julia Roberts", "Hugh Grant", "Rhys Ifans", "Emma Chambers"],
    "Se7en": ["Brad Pitt", "Morgan Freeman", "Gwyneth Paltrow", "Kevin Spacey"],
    "No Country for Old Men": ["Tommy Lee Jones", "Javier Bardem", "Josh Brolin", "Kelly Macdonald"],
    "Gone Girl": ["Ben Affleck", "Rosamund Pike", "Neil Patrick Harris", "Tyler Perry"],
    "The Silence of the Lambs": ["Jodie Foster", "Anthony Hopkins", "Scott Glenn", "Ted Levine"],
    "Prisoners": ["Hugh Jackman", "Jake Gyllenhaal", "Viola Davis", "Paul Dano"],
    "Zodiac": ["Jake Gyllenhaal", "Mark Ruffalo", "Robert Downey Jr.", "Anthony Edwards"],
    "Spirited Away": ["Rumi Hiiragi", "Miyu Irino", "Mari Natsuki", "Bunta Sugawara"],
    "Toy Story": ["Tom Hanks", "Tim Allen", "Don Rickles", "Annie Potts"],
    "Spider-Man: Into the Spider-Verse": ["Shameik Moore", "Hailee Steinfeld", "Jake Johnson", "Mahershala Ali"],
    "WALL-E": ["Ben Burtt", "Elissa Knight", "Jeff Garlin", "Fred Willard"],
    "The Iron Giant": ["Eli Marienthal", "Jennifer Aniston", "Harry Connick Jr.", "Vin Diesel"],
    "Coco": ["Anthony Gonzalez", "Gael García Bernal", "Benjamin Bratt", "Alanna Ubach"],
    "Up": ["Ed Asner", "Jordan Nagai", "Christopher Plummer", "Bob Peterson"],
    "The Lord of the Rings: The Fellowship of the Ring": ["Elijah Wood", "Ian McKellen", "Viggo Mortensen", "Sean Astin"],
    "Pan's Labyrinth": ["Ivana Baquero", "Sergi López", "Maribel Verdú", "Doug Jones"],
    "The Princess Bride": ["Cary Elwes", "Robin Wright", "Mandy Patinkin", "André the Giant"],
    "Harry Potter and the Prisoner of Azkaban": ["Daniel Radcliffe", "Rupert Grint", "Emma Watson", "Gary Oldman"],
    "Big Fish": ["Ewan McGregor", "Albert Finney", "Billy Crudup", "Jessica Lange"],
    "Free Solo": ["Alex Honnold", "Tommy Caldwell", "Sanni McCandless"],
    "Won't You Be My Neighbor?": ["Fred Rogers", "Joanne Rogers", "François Clemmons"],
    "Amy": ["Amy Winehouse", "Mitch Winehouse", "Mark Ronson"],
    "13th": ["Angela Davis", "Michelle Alexander", "Cory Booker", "Bryan Stevenson"],
    "Man on Wire": ["Philippe Petit", "Jean-Louis Blondeau", "Annie Allix"],
}

lines = []
lines.append("-- ============================================================================")
lines.append("-- Movie Roulette — seed data (generated by scripts/gen_seed.py)")
lines.append("-- ============================================================================")
lines.append("")
lines.append("truncate table public.watchlist, public.movie_genres, public.movies, public.genres restart identity cascade;")
lines.append("")

lines.append("insert into public.genres (slug, name) values")
lines.append(",\n".join(f"  ({s(slug)}, {s(name)})" for slug, name in GENRES) + ";")
lines.append("")

lines.append("insert into public.movies (title, release_year, director, runtime_minutes, rating, primary_genre, mood_tags, cast_members, synopsis) values")
rows = []
for title, year, director, runtime, rating, primary, genres, moods, blurb in MOVIES:
    rows.append(
        f"  ({s(title)}, {year}, {s(director)}, {runtime}, {rating}, {s(primary)}, {arr(moods)}, {arr(CAST.get(title, []))}, {s(blurb)})"
    )
lines.append(",\n".join(rows) + ";")
lines.append("")

lines.append("insert into public.movie_genres (movie_id, genre_slug) values")
mg_rows = []
for idx, (title, year, director, runtime, rating, primary, genres, moods, blurb) in enumerate(MOVIES, start=1):
    for g in genres:
        mg_rows.append(f"  ((select id from public.movies where title = {s(title)} and release_year = {year}), {s(g)})")
lines.append(",\n".join(mg_rows) + ";")
lines.append("")

print("\n".join(lines))
print(f"-- total movies: {len(MOVIES)}", file=__import__("sys").stderr)
